base_url = 'https://nrjais.com'
title = 'Neeraj Jaiswal'
description = 'Personel Blog'
highlight_code = true
build_search_index = true
generate_rss = true
theme = "zola-paper"
taxonomies = [
    {name = "tags", rss = true, paginate_by = 5},
]

[extra]
links = []
