---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - DOCKER_TAG=v0.9.0
  preview_output_directory: public
  preview_docker_image: j1mc/docker-zola
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: serve --drafts --port 8080
version: 0.55.6
