name: Site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site
      run: docker run -w /srv -v ${{ github.workspace }}:/srv j1mc/docker-zola build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: site
        PUBLISH_DIR: ./public
