name: Site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site
      run: docker run -w /srv -v ${{ github.workspace }}:/srv j1mc/docker-zola build
    - name: Setup public
      run: git init
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: public
        force: force
        directory: public
